### ISSUE TITLE
Cannot find files at start up

### ISSUE THREAD

**Issue by HeadClot** [Jordonbc/VREngineGuns#1]
Hey - I am using VR Engine and VREngineGuns together and I am getting the following error when I start up any project. This includes the VREngine Sample Project or a blank project with VREngine and VREngineGuns. 

![image](https://user-images.githubusercontent.com/1534098/103164427-54670100-47c8-11eb-8861-aff7fb1effc8.png)

**Comment by Jordonbc** [comment]
I have just updated the plugin to include the files but unfortunatly it will only work with UE 4.25.

**Comment by HeadClot** [comment]
Thank you @Jordonbc :)
